repos:
  - repo: https://github.com/ambv/black
    rev: 24.2.0
    hooks:
      - id: black
        language_version: python3.11
        args: ["--line-length", "88", "--target-version", "py311"]  # Keep line length consistent