services:
  musicbot:
    container_name: musicbot
    build:
      context: .
      dockerfile: Dockerfile
    hostname: musicbot
    platform: ${PLATFORM:-linux/amd64}
    env_file:
      - .env
    volumes:
      - ./config:/musicbot/config/
      - ./audio_cache:/musicbot/audio_cache
      - ./data:/musicbot/data
      - ./logs:/musicbot/logs
    networks:
      - musicbot
    working_dir: /musicbot

networks:
  musicbot:
    name: musicbot
    driver: bridge
